<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Tamanna" name="testcases.TestCases" tests="6" failures="1" timestamp="2021-03-13T19:52:07 BDT" time="38.412" errors="0">
  <testcase name="login_pass" time="7.016" classname="testcases.TestCases"/>
  <system-out/>
  <testcase name="invalid_usernamecase" time="4.992" classname="testcases.TestCases"/>
  <system-out/>
  <testcase name="invalid_passwordcase" time="5.035" classname="testcases.TestCases">
    <failure type="org.junit.ComparisonFailure" message="expected:&lt;[]&gt; but was:&lt;[Valid Username and password are required.]&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[]> but was:<[Valid Username and password are required.]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at pages.Username.toast_messaageclass(Username.java:48)
at testcases.TestCases.invalid_passwordcase(TestCases.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalid_passwordcase -->
  <system-out/>
  <testcase name="invalid_withoutusernamecase" time="6.106" classname="testcases.TestCases"/>
  <system-out/>
  <testcase name="invalid_withoutpasswordcase" time="6.460" classname="testcases.TestCases"/>
  <system-out/>
  <testcase name="bothfieldblankcase" time="8.803" classname="testcases.TestCases"/>
  <system-out/>
</testsuite> <!-- testcases.TestCases -->
